const lebronFact = [
  "LeBron James was born on December 30, 1984, in Akron, Ohio.",
  "He was drafted straight from high school as the 1st overall pick by the Cleveland Cavaliers in 2003.",
  "LeBron has won 4 NBA championships (2012, 2013, 2016, 2020).",
  "He is a 4-time NBA Finals MVP and 4-time NBA MVP.",
  "LeBron is the NBA's all-time leading scorer, surpassing Kareem Abdul-Jabbar's record in 2023.",
  "He's the only player to win NBA championships with 3 different teams (Cavaliers, Heat, Lakers).",
  "LeBron was the youngest player to score 30,000 career points at age 33.",
  "He has appeared in 10 NBA Finals (2007, 2011-2018, 2020).",
  "LeBron won Olympic gold medals in 2008 and 2012 with Team USA.",
  "He was named NBA Rookie of the Year in 2004.",
  "LeBron has been selected to the All-Star Game 19 times.",
  "He's one of only 4 players to record a triple-double in an NBA Finals Game 7.",
  "LeBron became the first player to lead both teams in all 5 major statistical categories in an NBA Finals series (2016).",
  "He founded the LeBron James Family Foundation and opened the I PROMISE School in Akron.",
  "LeBron was featured on the cover of Sports Illustrated at age 17 with the headline 'The Chosen One'.",
  "He's the first NBA player to accumulate $1 billion in career earnings while still actively playing.",
  "LeBron has his own production company called SpringHill Entertainment.",
  "He starred in the movie 'Space Jam: A New Legacy' in 2021.",
  "LeBron is 6'9\" tall and weighs approximately 250 pounds.",
  "He's known for his incredible basketball IQ and court vision.",
  "LeBron has never fouled out of an NBA game in his entire career.",
  "He's the youngest player to reach 25,000, 30,000, 35,000, and 38,000 career points.",
  "LeBron helped bring Cleveland its first major sports championship in 52 years in 2016.",
  "He's appeared in 8 consecutive NBA Finals from 2011-2018.",
  "LeBron was named one of Time Magazine's 100 Most Influential People multiple times.",
  "He owns a stake in Liverpool FC and the Boston Red Sox.",
  "LeBron has his own signature shoe line with Nike worth over $1 billion.",
  "He's known for his incredible longevity, playing at an elite level well into his late 30s.",
  "LeBron was the first player born in the 1980s to play in the NBA.",
  "He's recorded over 100 triple-doubles in his NBA career.",
  "LeBron's nickname 'King James' was popularized during his high school career.",
  "He played for St. Vincent-St. Mary High School in Akron, where he won 3 state championships.",
  "LeBron's high school games were sometimes televised nationally on ESPN.",
  "He was the youngest player to be drafted #1 overall at 18 years old.",
  "LeBron scored 25 points in his first NBA game against the Sacramento Kings.",
  "He's the only player to average at least 25 points, 5 rebounds, and 5 assists in his first 17 seasons.",
  "LeBron has played all 5 positions on the basketball court during his career.",
  "He's recorded at least 10 points in over 1,000 consecutive games.",
  "LeBron was the youngest player to reach 10,000, 15,000, and 20,000 career points.",
  "He's the only player to have 30,000+ points, 10,000+ rebounds, and 10,000+ assists.",
  "LeBron has played in the most playoff games in NBA history.",
  "He's the all-time leader in playoff points scored.",
  "LeBron is the only player to win Finals MVP with 3 different franchises.",
  "He averaged 8.5 assists per game in his first stint with Cleveland (2003-2010).",
  "LeBron's 'Decision' TV special in 2010 raised $2.5 million for charity.",
  "He formed the 'Big Three' with Dwyane Wade and Chris Bosh in Miami.",
  "LeBron's block on Andre Iguodala in Game 7 of the 2016 Finals is legendary.",
  "He's appeared on the cover of Vogue magazine with Gisele Bündchen.",
  "LeBron's son Bronny was drafted by the Lakers in 2024, making them the first father-son duo to play together.",
  "He's known for his pre-game chalk toss ritual.",
  "LeBron has his own talk show called 'The Shop' on HBO.",
  "He's executive produced several documentaries and TV shows.",
  "LeBron owns Blaze Pizza franchises across the United States.",
  "He's been featured in multiple video games including NBA 2K and his own mobile game.",
  "LeBron was named Sports Illustrated's Sportsman of the Year in 2012.",
  "He's the first active NBA player to become a billionaire.",
  "LeBron has his own media company called Uninterrupted.",
  "He's known for his incredible memory and ability to recall specific plays from years ago.",
  "LeBron spends over $1 million annually on his body maintenance and training.",
  "He's never averaged fewer than 20 points per game in any season.",
  "LeBron has played with over 200 different teammates throughout his career.",
  "He's the only player to win NBA championships in three different decades (2010s, 2020s).",
  "LeBron's jersey number 23 was retired by his high school.",
  "He briefly wore jersey number 6 with the Miami Heat to honor Michael Jordan.",
  "LeBron has appeared in multiple commercials, including memorable Nike ads.",
  "He's known for his clutch performances in elimination games.",
  "LeBron has the most 40-point games in NBA playoff history for players over 35.",
  "He's appeared in more Christmas Day games than any other player.",
  "LeBron was the face of the NBA's social justice initiatives.",
  "He's known for recruiting other superstars to join his teams.",
  "LeBron has the most triple-doubles in NBA Finals history.",
  "He's the only player to record a triple-double in an NBA Finals Game 6.",
  "LeBron's impact extends beyond basketball into fashion, business, and entertainment.",
  "He's considered one of the most complete players in NBA history.",
  "LeBron has mentored numerous young players throughout his career.",
  "He's known for his incredible passing ability for his size.",
  "LeBron holds the record for most points scored on Christmas Day.",
  "He's appeared in Sports Illustrated's top 50 athletes list multiple times.",
  "LeBron's influence helped change how NBA free agency works.",
  "He's known for his incredible work ethic and dedication to fitness.",
  "LeBron has played in 4 different decades (2000s, 2010s, 2020s, and potentially 2030s).",
  "He's the only player to lead a team back from a 3-1 deficit in the NBA Finals."
];

module.exports = lebronFact